///////////////////////////////////////////////////////////
//  Observer.cs
//  Implementation of the Interface Observer
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:34 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;



namespace Application {
    public interface Observer
    {

        void Notify();
        
    }//end Observer

}//end namespace Application