///////////////////////////////////////////////////////////
//  Reload.cs
//  Implementation of the Class Reload
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:40 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;



using Application;
namespace Application {
    public class Reload : User
    {
        /*
        private int amount;
        private string bankName;
        private int phoneNo;
        */

        private IList<Observer> Observers = new List<Observer>();

        /*
        public Reload()
        {

        }

        ~Reload()
        {

        }
        */

        public void notifyObserver()
        {
            foreach (Observer o in Observers)
            {
                o.Notify();
            }
        }


        /*
        public void payment()
        {

        }
        */


        public void success(Observer o)
        {
            Observers.Add(o);
        }

        public void unsuccess(Observer o)
        {
            Observers.Remove(o);
            Console.WriteLine("User has been notified about unsuccessful reload");
        }

        /*
        public void successObserver()
        {

        }

        public void unsuccessObserver()
        {

        }

        public void updateBalance()
        {

        }
        */
        

    }//end Reload

}//end namespace Application
                            
                            
                            