///////////////////////////////////////////////////////////
//  ReloadWallet.cs
//  Implementation of the Interface ReloadWallet
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:42 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;



using Application;
namespace Application {
    public class ReloadWallet
    {
        static void Main(string[] args)
        {
            Reload Ahmad = new Reload();

            Observer reload1 = new User();
            Observer reload2 = new User();
            Observer reload3 = new User();
            Observer reload4 = new User();

            Ahmad.success(reload1);
            Ahmad.success(reload2);
            Ahmad.success(reload3);

            Ahmad.notifyObserver();

            Ahmad.success(reload4);
            Console.WriteLine("Reload failed");
            Ahmad.unsuccess(reload4);

            Ahmad.notifyObserver();

            Console.ReadKey();
        }
    }//end ReloadWallet

}//end namespace Application